### PR TITLE
fixed bugs with command history

### LINKED ISSUE #5: command history traversal is buggy
* Sometimes "undefined" comes up when up arrow key is pressed (Happens because localstorage is storing historyIndex as a String. So instead of getting added 1 is being appended to historyIndex)
* Undefined index sometimes as historyIndex becomes equal to -1 or n due to the logic used
* Repitation of command at 0 index or n-1 index due to the logic used.
* Down arrow traversal even after typing

###  n is the size of history array

I will make a pull request to fix this 😃

### PR DESCRIPTION
**Pull request by cB-Abhinav-Gautam**
resolves #5 

you can test it here [My Fork](https://gotham13121997.github.io)

### CODE REVIEW

File: js/shell.js [hunk 1]
```diff
@@ -8,7 +8,8 @@ class Shell {
 
     localStorage.directory = 'root'
     localStorage.history = JSON.stringify('')
-
+    localStorage.historyIndex = -1 // Solves undefined command on refreshing the website
+    localStorage.goingThroughHistory = 'false' // To prevent down arrow traversal when not required
```
Comment (codebytere) [inline js/shell.js]: `goingThroughHistory` should be a boolean and update/checked accordingly

**Review by codebytere — CHANGES_REQUESTED** [review]

File: js/shell.js (hunk 1 above)
Comment (cB-Abhinav-Gautam) [reply js/shell.js]: done

**Review by codebytere — APPROVED** [review]
